package com.shiro.cn.sys.entity;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.ID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.ADDRESS
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.NAME
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.MID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    private String mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.FID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.ORDERID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    private String orderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.ID
     *
     * @return the value of T_PERMISSION.ID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.ID
     *
     * @param id the value for T_PERMISSION.ID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.ADDRESS
     *
     * @return the value of T_PERMISSION.ADDRESS
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.ADDRESS
     *
     * @param address the value for T_PERMISSION.ADDRESS
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.NAME
     *
     * @return the value of T_PERMISSION.NAME
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.NAME
     *
     * @param name the value for T_PERMISSION.NAME
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.MID
     *
     * @return the value of T_PERMISSION.MID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.MID
     *
     * @param mid the value for T_PERMISSION.MID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.FID
     *
     * @return the value of T_PERMISSION.FID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.FID
     *
     * @param fid the value for T_PERMISSION.FID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.ORDERID
     *
     * @return the value of T_PERMISSION.ORDERID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.ORDERID
     *
     * @param orderid the value for T_PERMISSION.ORDERID
     *
     * @mbggenerated Sun Jan 27 16:34:56 GMT+08:00 2019
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }
}