package com.shiro.cn.sys.entity;

import java.util.Date;

public class PermissionRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_ROLE.ID
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_ROLE.P_ID
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    private String pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_ROLE.R_ID
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    private String rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_ROLE.CJR
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    private String cjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_ROLE.CJSJ
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    private Date cjsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_ROLE.ID
     *
     * @return the value of T_PERMISSION_ROLE.ID
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_ROLE.ID
     *
     * @param id the value for T_PERMISSION_ROLE.ID
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_ROLE.P_ID
     *
     * @return the value of T_PERMISSION_ROLE.P_ID
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_ROLE.P_ID
     *
     * @param pId the value for T_PERMISSION_ROLE.P_ID
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    public void setpId(String pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_ROLE.R_ID
     *
     * @return the value of T_PERMISSION_ROLE.R_ID
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    public String getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_ROLE.R_ID
     *
     * @param rId the value for T_PERMISSION_ROLE.R_ID
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    public void setrId(String rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_ROLE.CJR
     *
     * @return the value of T_PERMISSION_ROLE.CJR
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_ROLE.CJR
     *
     * @param cjr the value for T_PERMISSION_ROLE.CJR
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    public void setCjr(String cjr) {
        this.cjr = cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_ROLE.CJSJ
     *
     * @return the value of T_PERMISSION_ROLE.CJSJ
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_ROLE.CJSJ
     *
     * @param cjsj the value for T_PERMISSION_ROLE.CJSJ
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }
}