package com.shiro.cn.sys.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public RoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("ROLE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("ROLE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("ROLE_NAME =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("ROLE_NAME <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("ROLE_NAME >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_NAME >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("ROLE_NAME <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("ROLE_NAME <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("ROLE_NAME like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("ROLE_NAME not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("ROLE_NAME in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("ROLE_NAME not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("ROLE_NAME between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("ROLE_NAME not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleInfoIsNull() {
            addCriterion("ROLE_INFO is null");
            return (Criteria) this;
        }

        public Criteria andRoleInfoIsNotNull() {
            addCriterion("ROLE_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andRoleInfoEqualTo(String value) {
            addCriterion("ROLE_INFO =", value, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleInfoNotEqualTo(String value) {
            addCriterion("ROLE_INFO <>", value, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleInfoGreaterThan(String value) {
            addCriterion("ROLE_INFO >", value, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleInfoGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_INFO >=", value, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleInfoLessThan(String value) {
            addCriterion("ROLE_INFO <", value, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleInfoLessThanOrEqualTo(String value) {
            addCriterion("ROLE_INFO <=", value, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleInfoLike(String value) {
            addCriterion("ROLE_INFO like", value, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleInfoNotLike(String value) {
            addCriterion("ROLE_INFO not like", value, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleInfoIn(List<String> values) {
            addCriterion("ROLE_INFO in", values, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleInfoNotIn(List<String> values) {
            addCriterion("ROLE_INFO not in", values, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleInfoBetween(String value1, String value2) {
            addCriterion("ROLE_INFO between", value1, value2, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleInfoNotBetween(String value1, String value2) {
            addCriterion("ROLE_INFO not between", value1, value2, "roleInfo");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjIsNull() {
            addCriterion("ROLE_CJSJ is null");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjIsNotNull() {
            addCriterion("ROLE_CJSJ is not null");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjEqualTo(Date value) {
            addCriterion("ROLE_CJSJ =", value, "roleCjsj");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjNotEqualTo(Date value) {
            addCriterion("ROLE_CJSJ <>", value, "roleCjsj");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjGreaterThan(Date value) {
            addCriterion("ROLE_CJSJ >", value, "roleCjsj");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjGreaterThanOrEqualTo(Date value) {
            addCriterion("ROLE_CJSJ >=", value, "roleCjsj");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjLessThan(Date value) {
            addCriterion("ROLE_CJSJ <", value, "roleCjsj");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjLessThanOrEqualTo(Date value) {
            addCriterion("ROLE_CJSJ <=", value, "roleCjsj");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjIn(List<Date> values) {
            addCriterion("ROLE_CJSJ in", values, "roleCjsj");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjNotIn(List<Date> values) {
            addCriterion("ROLE_CJSJ not in", values, "roleCjsj");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjBetween(Date value1, Date value2) {
            addCriterion("ROLE_CJSJ between", value1, value2, "roleCjsj");
            return (Criteria) this;
        }

        public Criteria andRoleCjsjNotBetween(Date value1, Date value2) {
            addCriterion("ROLE_CJSJ not between", value1, value2, "roleCjsj");
            return (Criteria) this;
        }

        public Criteria andRoleCjrIsNull() {
            addCriterion("ROLE_CJR is null");
            return (Criteria) this;
        }

        public Criteria andRoleCjrIsNotNull() {
            addCriterion("ROLE_CJR is not null");
            return (Criteria) this;
        }

        public Criteria andRoleCjrEqualTo(String value) {
            addCriterion("ROLE_CJR =", value, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleCjrNotEqualTo(String value) {
            addCriterion("ROLE_CJR <>", value, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleCjrGreaterThan(String value) {
            addCriterion("ROLE_CJR >", value, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleCjrGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_CJR >=", value, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleCjrLessThan(String value) {
            addCriterion("ROLE_CJR <", value, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleCjrLessThanOrEqualTo(String value) {
            addCriterion("ROLE_CJR <=", value, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleCjrLike(String value) {
            addCriterion("ROLE_CJR like", value, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleCjrNotLike(String value) {
            addCriterion("ROLE_CJR not like", value, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleCjrIn(List<String> values) {
            addCriterion("ROLE_CJR in", values, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleCjrNotIn(List<String> values) {
            addCriterion("ROLE_CJR not in", values, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleCjrBetween(String value1, String value2) {
            addCriterion("ROLE_CJR between", value1, value2, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleCjrNotBetween(String value1, String value2) {
            addCriterion("ROLE_CJR not between", value1, value2, "roleCjr");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjIsNull() {
            addCriterion("ROLE_GXSJ is null");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjIsNotNull() {
            addCriterion("ROLE_GXSJ is not null");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjEqualTo(Date value) {
            addCriterion("ROLE_GXSJ =", value, "roleGxsj");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjNotEqualTo(Date value) {
            addCriterion("ROLE_GXSJ <>", value, "roleGxsj");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjGreaterThan(Date value) {
            addCriterion("ROLE_GXSJ >", value, "roleGxsj");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjGreaterThanOrEqualTo(Date value) {
            addCriterion("ROLE_GXSJ >=", value, "roleGxsj");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjLessThan(Date value) {
            addCriterion("ROLE_GXSJ <", value, "roleGxsj");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjLessThanOrEqualTo(Date value) {
            addCriterion("ROLE_GXSJ <=", value, "roleGxsj");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjIn(List<Date> values) {
            addCriterion("ROLE_GXSJ in", values, "roleGxsj");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjNotIn(List<Date> values) {
            addCriterion("ROLE_GXSJ not in", values, "roleGxsj");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjBetween(Date value1, Date value2) {
            addCriterion("ROLE_GXSJ between", value1, value2, "roleGxsj");
            return (Criteria) this;
        }

        public Criteria andRoleGxsjNotBetween(Date value1, Date value2) {
            addCriterion("ROLE_GXSJ not between", value1, value2, "roleGxsj");
            return (Criteria) this;
        }

        public Criteria andRoleGxrIsNull() {
            addCriterion("ROLE_GXR is null");
            return (Criteria) this;
        }

        public Criteria andRoleGxrIsNotNull() {
            addCriterion("ROLE_GXR is not null");
            return (Criteria) this;
        }

        public Criteria andRoleGxrEqualTo(String value) {
            addCriterion("ROLE_GXR =", value, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andRoleGxrNotEqualTo(String value) {
            addCriterion("ROLE_GXR <>", value, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andRoleGxrGreaterThan(String value) {
            addCriterion("ROLE_GXR >", value, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andRoleGxrGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_GXR >=", value, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andRoleGxrLessThan(String value) {
            addCriterion("ROLE_GXR <", value, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andRoleGxrLessThanOrEqualTo(String value) {
            addCriterion("ROLE_GXR <=", value, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andRoleGxrLike(String value) {
            addCriterion("ROLE_GXR like", value, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andRoleGxrNotLike(String value) {
            addCriterion("ROLE_GXR not like", value, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andRoleGxrIn(List<String> values) {
            addCriterion("ROLE_GXR in", values, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andRoleGxrNotIn(List<String> values) {
            addCriterion("ROLE_GXR not in", values, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andRoleGxrBetween(String value1, String value2) {
            addCriterion("ROLE_GXR between", value1, value2, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andRoleGxrNotBetween(String value1, String value2) {
            addCriterion("ROLE_GXR not between", value1, value2, "roleGxr");
            return (Criteria) this;
        }

        public Criteria andIssupIsNull() {
            addCriterion("ISSUP is null");
            return (Criteria) this;
        }

        public Criteria andIssupIsNotNull() {
            addCriterion("ISSUP is not null");
            return (Criteria) this;
        }

        public Criteria andIssupEqualTo(String value) {
            addCriterion("ISSUP =", value, "issup");
            return (Criteria) this;
        }

        public Criteria andIssupNotEqualTo(String value) {
            addCriterion("ISSUP <>", value, "issup");
            return (Criteria) this;
        }

        public Criteria andIssupGreaterThan(String value) {
            addCriterion("ISSUP >", value, "issup");
            return (Criteria) this;
        }

        public Criteria andIssupGreaterThanOrEqualTo(String value) {
            addCriterion("ISSUP >=", value, "issup");
            return (Criteria) this;
        }

        public Criteria andIssupLessThan(String value) {
            addCriterion("ISSUP <", value, "issup");
            return (Criteria) this;
        }

        public Criteria andIssupLessThanOrEqualTo(String value) {
            addCriterion("ISSUP <=", value, "issup");
            return (Criteria) this;
        }

        public Criteria andIssupLike(String value) {
            addCriterion("ISSUP like", value, "issup");
            return (Criteria) this;
        }

        public Criteria andIssupNotLike(String value) {
            addCriterion("ISSUP not like", value, "issup");
            return (Criteria) this;
        }

        public Criteria andIssupIn(List<String> values) {
            addCriterion("ISSUP in", values, "issup");
            return (Criteria) this;
        }

        public Criteria andIssupNotIn(List<String> values) {
            addCriterion("ISSUP not in", values, "issup");
            return (Criteria) this;
        }

        public Criteria andIssupBetween(String value1, String value2) {
            addCriterion("ISSUP between", value1, value2, "issup");
            return (Criteria) this;
        }

        public Criteria andIssupNotBetween(String value1, String value2) {
            addCriterion("ISSUP not between", value1, value2, "issup");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ROLE
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}