package com.shiro.cn.sys.entity;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ID
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLE_NAME
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLE_INFO
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    private String roleInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLE_CJSJ
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    private Date roleCjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLE_CJR
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    private String roleCjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLE_GXSJ
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    private Date roleGxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLE_GXR
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    private String roleGxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ISSUP
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    private String issup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ID
     *
     * @return the value of T_ROLE.ID
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ID
     *
     * @param id the value for T_ROLE.ID
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLE_NAME
     *
     * @return the value of T_ROLE.ROLE_NAME
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLE_NAME
     *
     * @param roleName the value for T_ROLE.ROLE_NAME
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLE_INFO
     *
     * @return the value of T_ROLE.ROLE_INFO
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public String getRoleInfo() {
        return roleInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLE_INFO
     *
     * @param roleInfo the value for T_ROLE.ROLE_INFO
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void setRoleInfo(String roleInfo) {
        this.roleInfo = roleInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLE_CJSJ
     *
     * @return the value of T_ROLE.ROLE_CJSJ
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public Date getRoleCjsj() {
        return roleCjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLE_CJSJ
     *
     * @param roleCjsj the value for T_ROLE.ROLE_CJSJ
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void setRoleCjsj(Date roleCjsj) {
        this.roleCjsj = roleCjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLE_CJR
     *
     * @return the value of T_ROLE.ROLE_CJR
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public String getRoleCjr() {
        return roleCjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLE_CJR
     *
     * @param roleCjr the value for T_ROLE.ROLE_CJR
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void setRoleCjr(String roleCjr) {
        this.roleCjr = roleCjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLE_GXSJ
     *
     * @return the value of T_ROLE.ROLE_GXSJ
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public Date getRoleGxsj() {
        return roleGxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLE_GXSJ
     *
     * @param roleGxsj the value for T_ROLE.ROLE_GXSJ
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void setRoleGxsj(Date roleGxsj) {
        this.roleGxsj = roleGxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLE_GXR
     *
     * @return the value of T_ROLE.ROLE_GXR
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public String getRoleGxr() {
        return roleGxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLE_GXR
     *
     * @param roleGxr the value for T_ROLE.ROLE_GXR
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void setRoleGxr(String roleGxr) {
        this.roleGxr = roleGxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ISSUP
     *
     * @return the value of T_ROLE.ISSUP
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public String getIssup() {
        return issup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ISSUP
     *
     * @param issup the value for T_ROLE.ISSUP
     *
     * @mbggenerated Sun Jan 27 16:43:21 GMT+08:00 2019
     */
    public void setIssup(String issup) {
        this.issup = issup;
    }
}