package com.shiro.cn.sys.entity;

import java.util.Date;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE.ID
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE.U_ID
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE.R_ID
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    private String rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE.CJR
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    private String cjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE.CJSJ
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    private Date cjsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE.ID
     *
     * @return the value of T_USER_ROLE.ID
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE.ID
     *
     * @param id the value for T_USER_ROLE.ID
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE.U_ID
     *
     * @return the value of T_USER_ROLE.U_ID
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE.U_ID
     *
     * @param uId the value for T_USER_ROLE.U_ID
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    public void setuId(String uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE.R_ID
     *
     * @return the value of T_USER_ROLE.R_ID
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    public String getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE.R_ID
     *
     * @param rId the value for T_USER_ROLE.R_ID
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    public void setrId(String rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE.CJR
     *
     * @return the value of T_USER_ROLE.CJR
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE.CJR
     *
     * @param cjr the value for T_USER_ROLE.CJR
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    public void setCjr(String cjr) {
        this.cjr = cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE.CJSJ
     *
     * @return the value of T_USER_ROLE.CJSJ
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE.CJSJ
     *
     * @param cjsj the value for T_USER_ROLE.CJSJ
     *
     * @mbggenerated Sun Jan 27 16:42:13 GMT+08:00 2019
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }
}