package com.shiro.cn.sys.entity;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.ID
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.NAME
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.PWD
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.CREATEDATE
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.EIDTDATE
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    private Date eidtdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.INFO
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.PHONE
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.EMAIL
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.DEPTNO_ID
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    private String deptnoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.ID
     *
     * @return the value of T_USER.ID
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.ID
     *
     * @param id the value for T_USER.ID
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.NAME
     *
     * @return the value of T_USER.NAME
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.NAME
     *
     * @param name the value for T_USER.NAME
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.PWD
     *
     * @return the value of T_USER.PWD
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.PWD
     *
     * @param pwd the value for T_USER.PWD
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.CREATEDATE
     *
     * @return the value of T_USER.CREATEDATE
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.CREATEDATE
     *
     * @param createdate the value for T_USER.CREATEDATE
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.EIDTDATE
     *
     * @return the value of T_USER.EIDTDATE
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public Date getEidtdate() {
        return eidtdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.EIDTDATE
     *
     * @param eidtdate the value for T_USER.EIDTDATE
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public void setEidtdate(Date eidtdate) {
        this.eidtdate = eidtdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.INFO
     *
     * @return the value of T_USER.INFO
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.INFO
     *
     * @param info the value for T_USER.INFO
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.PHONE
     *
     * @return the value of T_USER.PHONE
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.PHONE
     *
     * @param phone the value for T_USER.PHONE
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.EMAIL
     *
     * @return the value of T_USER.EMAIL
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.EMAIL
     *
     * @param email the value for T_USER.EMAIL
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.DEPTNO_ID
     *
     * @return the value of T_USER.DEPTNO_ID
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public String getDeptnoId() {
        return deptnoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.DEPTNO_ID
     *
     * @param deptnoId the value for T_USER.DEPTNO_ID
     *
     * @mbggenerated Sun Jan 27 16:42:45 GMT+08:00 2019
     */
    public void setDeptnoId(String deptnoId) {
        this.deptnoId = deptnoId;
    }
}