package com.shiro.cn.sys.mapper;

import com.shiro.cn.sys.entity.PermissionRole;
import com.shiro.cn.sys.entity.PermissionRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PermissionRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_ROLE
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    int countByExample(PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_ROLE
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    int deleteByExample(PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_ROLE
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_ROLE
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    int insert(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_ROLE
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    int insertSelective(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_ROLE
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    List<PermissionRole> selectByExample(PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_ROLE
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    PermissionRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_ROLE
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") PermissionRole record, @Param("example") PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_ROLE
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    int updateByExample(@Param("record") PermissionRole record, @Param("example") PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_ROLE
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_ROLE
     *
     * @mbggenerated Sun Jan 27 16:39:16 GMT+08:00 2019
     */
    int updateByPrimaryKey(PermissionRole record);
}